### ISSUE TITLE
spetlr-test job submit - KeyError 'instance_pools'

### ISSUE THREAD

**Issue by LauJohansson** [spetlr-org/spetlr-tools#13]
When using spetlr-test job submit - I encounter this error:
```
Run spetlr-test-job submit `
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/bin/spetlr-test-job", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/spetlrtools/test_job/main.py", line 19, in main
    args.func(args)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/spetlrtools/test_job/submit.py", line [16](https://github.com/spetlr-org/spetlr/actions/runs/5419960817/jobs/9853587779?pr=18#step:9:17)6, in submit_main
    submit(
  File "/opt/hostedtoolcache/Python/3.8.[17](https://github.com/spetlr-org/spetlr/actions/runs/5419960817/jobs/9853587779?pr=18#step:9:18)/x64/lib/python3.8/site-packages/spetlrtools/test_job/submit.py", line 298, in submit
    pools = PoolBoy()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/spetlrtools/test_job/submit.py", line [24](https://github.com/spetlr-org/spetlr/actions/runs/5419960817/jobs/9853587779?pr=18#step:9:25)8, in __init__
    self._lookup = self.get_instance_pools()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/spetlrtools/test_job/submit.py", line [26](https://github.com/spetlr-org/spetlr/actions/runs/5419960817/jobs/9853587779?pr=18#step:9:27)3, in get_instance_pools
    for pool in pool_data["instance_pools"]
KeyError: 'instance_pools'
Error: Process completed with exit code 1.
```

**Comment by LauJohansson** [comment]
#41
